### ISSUE TITLE
[已解决]文件名长度限制，不显示列表

### ISSUE THREAD

**Issue by wwng2333** [ling-drag0n/CloudPaste-old#1]
如题，`8k_iphone_wallpaper_5c549c6a-1389-4cd2-aa61-b97193f34dfe.png`上传不了，将文件名改短以后上传正常，故怀疑文件名长度是否有限制？

**Comment by wwng2333** [comment]
![image](https://github.com/user-attachments/assets/92986406-d6a1-456e-b4e4-5d4726371f43)
还发现一个问题，管理里面不显示已经上传的文件/文本

![image](https://github.com/user-attachments/assets/0ca3fe8e-6e18-46c5-9c42-6e064038e305)
在F12里面看是已经拿到列表了，但是没正常显示出来

**Comment by ling-drag0n** [comment]
> 如题，`8k_iphone_wallpaper_5c549c6a-1389-4cd2-aa61-b97193f34dfe.png`上传不了，将文件名改短以后上传正常，故怀疑文件名长度是否有限制？

我没设置文件名的限制哦，只设置了文件上传的大小最大为25MB（可自己修改大小）。我试了一下你的文件名是成功的。

**Comment by ling-drag0n** [comment]
看看KV和R2有存储到信息吗

**Comment by ling-drag0n** [comment]
唯一有限制的可能就只有Cloudflare R2 的元数据 2KB限制，一般来说都超不了

**Comment by wwng2333** [comment]
> 唯一有限制的可能就只有Cloudflare R2 的元数据 2KB限制，一般来说都超不了

我试了一下，现在又可以了，可能是网络波动导致的问题。

**Comment by wwng2333** [comment]
> ![image](https://private-user-images.githubusercontent.com/17147265/389207183-92986406-d6a1-456e-b4e4-5d4726371f43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MzM1MTAsIm5iZiI6MTczMjQzMzIxMCwicGF0aCI6Ii8xNzE0NzI2NS8zODkyMDcxODMtOTI5ODY0MDYtZDZhMS00NTZlLWI0ZTQtNWQ0NzI2MzcxZjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDA3MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYmM3OTYyYWRjNjQ1MzRlNWRiNTIyYjZiMzBhMDEwYjQ2NDVjY2I3ZjA4NWFhNjMzNDQyNjZiYWVjZWFhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Al7wH5fvMU4bya1nujT0xssYeGjNb4xHlwKpg0ACbO0) 还发现一个问题，管理里面不显示已经上传的文件/文本
> 
> ![image](https://private-user-images.githubusercontent.com/17147265/389207377-0ca3fe8e-6e18-46c5-9c42-6e064038e305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MzM1MTAsIm5iZiI6MTczMjQzMzIxMCwicGF0aCI6Ii8xNzE0NzI2NS8zODkyMDczNzctMGNhM2ZlOGUtNmUxOC00NmM1LTljNDItNmUwNjQwMzhlMzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDA3MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OWVmMTFmZmM3MzkwMzg0N2IyM2E5OTVhMTdjM2EzMTY4MDM1YzVkZmVmMzMyNDJmMWVkYjVmODk1OWRhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x0UAxoYCG0WjXPrIuJ1DWeGjnH0rwkixD6QKjVyfDSU) 在F12里面看是已经拿到列表了，但是没正常显示出来

问题已解决，原因是adblock阻止了cloudflare的`beacon.min.js`
