### ISSUE TITLE
暗色模式

### ISSUE THREAD

**Issue by iwvw** [ling-drag0n/CloudPaste-old#10]
大佬可以适配吗？能跟随系统自动切换最好

**Comment by ling-drag0n** [comment]
适配了，但技术原因可能还是有点小瑕疵，能用亮色就亮色吧😢

**Comment by iwvw** [comment]
> 适配了，但技术原因可能还是有点小瑕疵，能用亮色就亮色吧😢

了解
还有能适配下pwa就更好了
