### ISSUE TITLE
是否能提供直链下载？

### ISSUE THREAD

**Issue by QAbot-zh** [ling-drag0n/CloudPaste-old#12]
当前分享链接是跳转到网页，提供按钮下载方式，是否可以同时再生成一个下载直链，方便不经过网页操作直接下载文件内容呢？比如在给服务器发送一些文件的时候就会很方便

**Comment by ling-drag0n** [comment]
可以的，已添加作为可选项，管理页面可复制直链链接，形式为：https://your-domain/download/fileId
如果要服务器发送文件的话：
无密码：curl -O https://your-domain/download/fileId
有密码：curl -H "X-Password: your-password" -O https://your-domain/download/fileId

**Comment by QAbot-zh** [comment]
太棒了，好用！！

**Comment by musk1024** [comment]
> 可以的，已添加作为可选项，管理页面可复制直链链接，形式为：https://your-domain/download/fileId 如果要服务器发送文件的话： 无密码：curl -O https://your-domain/download/fileId 有密码：curl -H "X-Password: your-password" -O https://your-domain/download/fileId

提一个小功能，在下载的时候，是否可以提供一个进度条？
