### ISSUE TITLE
[已解决]测试&&建议

### ISSUE THREAD

**Issue by kpastriu** [ling-drag0n/CloudPaste-old#2]
疑问：文件上传和文本上传开关好像每次都需要开才行！
bug：文件上传测试似乎失败了
bug：自定义后缀似乎有问题，报错【Cannot read properties of undefined (reading 'get')】

**Comment by ling-drag0n** [comment]
检查一下KV和R2命名和绑定哦

**Comment by ling-drag0n** [comment]
> 疑问：文件上传和文本上传开关好像每次都需要开才行！ bug：文件上传测试似乎失败了 bug：自定义后缀似乎有问题，报错【Cannot read properties of undefined (reading 'get')】

为了防止有时候可能会忘记关闭导致被盗刷（默认是关闭），文本上传和文件上传设置的状态就没写入KV存储状态，所以登录管理员开启后，不刷新页面状态还是在的。
