### ISSUE TITLE
功能增加：持久化保存文本、文件上传状态，增加文件中转站

### ISSUE THREAD

**Issue by musk1024** [ling-drag0n/CloudPaste-old#8]
试用了一下，感觉分享功能做的很好，希望能增加以下两个feature：
1. 可以将管理员文本、文件上传状态写入KV存储状态，使得每一次登陆管理员账户都不用手动进行开启。
2. 增加一个类似于文件中转站的功能，可以在不用生成在分享链接的前提下，实现文件的临时保存。

感谢为项目的付出

**Comment by ling-drag0n** [comment]
1.已完成
2.功能和普通的感觉有点冲突，可能不考虑。
